### ISSUE TITLE
100% CPU use and no output on Ubuntu 15.10 with newer kernel

### ISSUE THREAD

**Issue by tv42** [tv42/alone#1]
Not sure yet what change caused the difference.

**Comment by gaffo** [comment]
I'm on Ubuntu 14.04 3.13.0-67-generic with qemu 2.0.0 (Debian 2.0.0+dfsg-2ubuntu1.19) and same issue

**Comment by gaffo** [comment]
From Ubuntu 14.04 3.13.0-67-generic with qemu 2.0.0 (Debian 2.0.0+dfsg-2ubuntu1.19)

qemu-system-x86_64 -kernel /boot/vmlinux-3.13-0-67-generic

boots just fine (once I allow read to that image)

qemu-system-x86_64 -kernel /boot/vmlinux-3.13-0-67-generic 
complains about no root fs

Same on Ubuntu 14.04 3.13.0-66

**Comment by gaffo** [comment]
bzImage is being built from commit ce5c2d2c256a4c

**Comment by gaffo** [comment]
if I build from 002acf1fc16cf60e6034 it boots. So it's definitely a build thing.

I think your build linux script should pull a stable tag from a variable and use that instead of using head

**Comment by tv42** [comment]
Something seems to change what the kernel config ends up being, leading to `CONFIG_PRINTK` and friends being disabled, and that's probably hiding the real reason. Still debugging..

**Comment by gaffo** [comment]
v4.3 of the kernel fails, working my way back major revs to find what works

**Comment by gaffo** [comment]
v4.2 fails

**Comment by gaffo** [comment]
v4.1 fails

**Comment by gaffo** [comment]
v4.0 fails, going to 3's

**Comment by gaffo** [comment]
v3.19 fails
v3.18 fails

**Comment by gaffo** [comment]
v3.17 fails... hoping one of these works sometime or I'm going (around v3.13) or I'm going to have to do it again with clean builds...

**Comment by gaffo** [comment]
v3.16 fails

**Comment by gaffo** [comment]
v3.15 fails

**Comment by gaffo** [comment]
v3.14 boots
